# Numpy

## 1. List vs NumPy Array

In [1]:
import numpy as np

In [2]:
# Add a list of elements
a = [1, 2, 3]
b = [4, 5]
a.extend(b)
print(a)

a = np.array([1, 2, 3])
b = np.array([4, 5])
np.append(a, b)

[1, 2, 3, 4, 5]


array([1, 2, 3, 4, 5])

In [3]:
# Delete element based on index
a = [1, 2, 3]
a.pop(1)
print(a)

l = np.array([1, 2, 3])
np.delete(l, 1)

[1, 3]


array([1, 3])

In [4]:
# Delete element based on value
a = [1, 2, 9]
a.remove(9)
print(a)

l = np.array([1, 2, 9])
np.delete(l, np.where(l == 9)[0])

[1, 2]


array([1, 2])

In [5]:
# Index
arr = [9, 8, 7, 9]
print(arr.index(9))

arr2 = np.array([9, 8, 7, 9, 9])
print(np.where(arr2 == 9)[0])
print(np.where(arr2 == 9)[0][0])
print(np.where(arr2 == 9)[0][1])
print(np.where(arr2 == 9)[0][2])


0
[0 3 4]
0
3
4


In [6]:
# Zip-like operation

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 9, 8, 7, 6])

for i, j in np.dstack((arr1, arr2))[0]:
    print(i, j)


print(np.dstack((arr1, arr2))[0]) 
print(np.dstack((arr1, arr2))[0][0])    # [1 10]
print(np.dstack((arr1, arr2))[0][1])    # [2 9]



1 10
2 9
3 8
4 7
5 6
[[ 1 10]
 [ 2  9]
 [ 3  8]
 [ 4  7]
 [ 5  6]]
[ 1 10]
[2 9]


In [7]:
# Enumerate
arr = np.array([1, 2, 3, 4, 5])

for i, val in np.ndenumerate(arr):
    print(i, val)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


## 2. Advanced techniques

In [8]:
# Int array indexing

arr = np.array([5, 6, 7, 8])
print(arr[2:4])     # [7 8]
print(arr[[2, 3]])  # [7 8]
print(arr[[0, 3]])  # [5 8]

# Boolean array indexing

print(arr[arr > 3])     # [5 6 7 8]
print(arr[arr != 6])    # [5 7 8]  

# Array manipulation

arr2 = np.array([
    [1, 2],
    [4, 5],
    [7, 8]
])

print(arr2.reshape(1, 6))   # [[1 2 4 5 7 8]]
print(arr2.reshape(6, 1))   # [[1], [2], [4], [5], [7], [8]]

print(arr2.reshape(2, 3))   # [[1 2 4], [5 7 8]]

# Concatenation

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[1, 2], [3, 4], [5, 6]])

print(np.concatenate((arr3, arr4))) # default axis = 0
print(np.concatenate((arr3, arr4), axis=0))
# [[1 2]
#  [3 4]
#  [5 6]
#  [1 2]
#  [3 4]
#  [5 6]]
print(np.concatenate((arr3, arr4), axis=1))
# [[1 2 1 2]
#  [3 4 3 4]
#  [5 6 5 6]]

[7 8]
[7 8]
[5 8]
[5 6 7 8]
[5 7 8]
[[1 2 4 5 7 8]]
[[1]
 [2]
 [4]
 [5]
 [7]
 [8]]
[[1 2 4]
 [5 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]
[[1 2 1 2]
 [3 4 3 4]
 [5 6 5 6]]


In [9]:
#Broadcasting and vectorization
a = np.array([[1, 2], [3, 4]])
b = np.array([1, 1])

print(a + b)

[[2 3]
 [4 5]]


In [10]:
# Reshape
arr = np.arange(1, 9)
print(arr.reshape((2, 4), order='C'))
print(arr.reshape((2, 4), order='F'))
print(arr.reshape((4, 2), order='C'))
print(arr.reshape((4, 2), order='F'))

[[1 2 3 4]
 [5 6 7 8]]
[[1 3 5 7]
 [2 4 6 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
